### ISSUE TITLE
kicad_prl is used for what?

### ISSUE THREAD

**Issue by leoheck** [MisterHW/KiCad-Design-Examples#1]
Hi, MisterHW I am seeing this new kicad_prl file in your project but I could not find any info on the internet. What is the use of it?

**Comment by MisterHW** [comment]
it contains UI settings now locally saved with the project and is automatically added to the project.
According to KiCad source, its official name is ProjectLocalSettings. It's very subtle / self-evident at first, but details like the state of high contrast mode, search filters, and visible / highlighted items are now preserved between sessions :)

**Comment by leoheck** [comment]
Oh, perfect, thank you for explaining this. This is actually a really good new feature for me.
Ah and thank you a lot for this sample project! It will help a lot start using this new design constraints.
